### PR TITLE
accept all TLS certs for localhost

### PR DESCRIPTION
**Pull request by neelance**

### CODE REVIEW

**Comment by gbbr** [comment]
I am not familiar with the context, but in terms of code LGTM

**Comment by neelance** [comment]
The idea is to allow localhost connections regardless of the certificate used, because the cert is usually only valid for the external domain.

**Comment by gbbr** [comment]
Do you wanna add a map of `localhost`, `127.0.0.1`, `::1` just in case? Would that be a better idea? Is there a way we can cover more variations of localhost?

**Comment by keegancsmith** [comment]
shipit. `localhost` should be good enough. In fact after a quick check there are even places in `net/http` code where they just check `localhost`.

**Comment by gbbr** [comment]
:shipit:

**Pull request merged**
