### PR TITLE
added ListResponse to RefList and ExampleList

### PR DESCRIPTION
**Pull request by neelance**

### CODE REVIEW

**Comment by slimsag** [comment]
I wonder why the white-space on some items changed, though? (not very important)

LGTM overall, merge away. 

P.S. Ping me when you send a change to implement this too, I'd like to see it (I can review it too, if you like).

**Comment by neelance** [comment]
The whitespace changes are because Atom automatically trims whitespace at the end of each line.

**Comment by slimsag** [comment]
@neelance That's actually really nice. LGTM

**Comment by shurcooL** [comment]
LGTM.

Sublime Text does that too if you set `"trim_trailing_white_space_on_save": true` in preferences. It's like a mini-gofmt-on-save for non .go files.

**Pull request merged**
