### PR TITLE
moved DefFormatStrings to srclib/graph

### PR DESCRIPTION
**Pull request by neelance**

### CODE REVIEW

**Comment by gbbr** [comment]
Is this fixing any specific bug? If not, should we be making breaking changes so close to release? Also, has the srclib change already been made? If it has, does this PR depend on another PR?

**Comment by neelance** [comment]
Yeah, the other one is https://github.com/sourcegraph/srclib/pull/178. This is necessary towards the goal of getting rid of the def formatters and thus the srclib toolchain dependencies. `DefFormatStrings` is not used very often, so the change has a low impact.

**Comment by sqs** [comment]
lgtm

**Comment by shurcooL** [comment]
LGTM.

**Pull request merged**
