### PR TITLE
changed type of Def.DocHTML to pbtypes.HTML

### PR DESCRIPTION
**Pull request by neelance**

### CODE REVIEW

**Comment by neelance** [comment]
Please just review, don't merge because this requires simultaneous changes in the sourcegraph repo.

**Comment by keegancsmith** [comment]
looks good to me

**Comment by shurcooL** [comment]
This looks like a backwards incompatible change, since you're reusing the same id. Are we allowed to do that, or should it be a new id?

**Comment by neelance** [comment]
@shurcooL Yeah, I don't know what our current policy is. But if we're getting serious about keeping the format, then we should also start paying the same attention to semantic changes (in the implementation of the API in the main repository).

**Comment by beyang** [comment]
Given there are no external dependents of the API, let's go ahead and break back compat. Later we will have to worry about it but not a problem at the moment. 






On Sat, Sep 5, 2015 at 3:34 AM -0700, "Richard Musiol" <notifications@github.com> wrote:












@shurcooL Yeah, I don't know what our current policy is. But if we're getting serious about keeping the format, then we should also start paying the same attention to semantic changes (in the implementation of the API in the main repository).

**Pull request merged**
